# Generated by Django 4.2.7 on 2025-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.IntegerField()),
                ('reps_completed', models.IntegerField(blank=True, null=True)),
                ('weight_used', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Goal'), ('exercise', 'Exercise Goal'), ('habit', 'Habit Goal')], max_length=20)),
                ('target_value', models.FloatField(blank=True, help_text='Target value (e.g., target weight)', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('notes', models.TextField(blank=True)),
                ('workout_duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('poor', 'Poor')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
